Vood 171 gif recording no longer working
GinoCardillo-OST/Visual-OO-Debugger pull request #36
Opened 2022-04-29 07:40 UTC by PascalSchuermannOst

2022-05-01 16:52 UTC, GinoCardillo-OST commented on src/node-modules-accessor/nodeModulesAccessor.ts
>          includeFolder: true,
```suggestion
```
The min.js is enough.

2022-05-01 16:55 UTC, GinoCardillo-OST commented
Recording the Gif is extremely slow but the results is good.
Recording the webm is faster but the results is worse.
Unfortunate...

2022-05-02 08:39 UTC, alexandre-lagadec-ost approved these changes

2022-05-03 14:01 UTC, alexandre-lagadec-ost requested changes

2022-05-03 14:01 UTC, alexandre-lagadec-ost commented on media/html/visjsDebuggerPanel.html
> +      function stopRecordingVisjsGif(render) {
```suggestion
      function stopRecordingVisjsGif() {
```

2022-05-03 14:01 UTC, alexandre-lagadec-ost commented on media/html/visjsDebuggerPanel.html
> +      function stopRecordingVisjsWebm(render) {
```suggestion
      function stopRecordingVisjsWebm() {
```

2022-05-18 15:01 UTC, alexandre-lagadec-ost approved these changes

2022-05-24 10:37 UTC, closed without merging